language: go

go:
  - 1.17.x
  - 1.x

before_install:
  - go get -t -v ./...
  - go vet ./...

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)